export default {
  GET_AANBIEDINGEN: 'GET_AANBIEDINGEN',
  GET_AANBIEDINGEN_FULFILLED: 'GET_AANBIEDINGEN_FULFILLED',
  GET_AANBIEDINGEN_LOADING: 'GET_AANBIEDINGEN_LOADING',
  GET_AANBIEDINGEN_FAILED: 'GET_AANBIEDINGEN_FAILED',
};
