export default {
  GET_AUTOMATEN: 'GET_AUTOMATEN',
  GET_AUTOMATEN_FULFILLED: 'GET_AUTOMATEN_FULFILLED',
  GET_AUTOMATEN_LOADING: 'GET_AUTOMATEN_LOADING',
  GET_AUTOMATEN_FAILED: 'GET_AUTOMATEN_FAILED',
};
